apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #pv name
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi