apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #pv name
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
  purpose: "ebs-static-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-pvc-claim 

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer  # tyoe shoul be mention here, if we don't mention it will take cluster IP by default
  selector: # labels are used as selectors
    purpose: "ebs-static-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007